import {
    User,
    DeliveryPartner,
    Order,
    Shop,
    DashboardStats,
} from './types';

// Mock Users
export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Priya Sharma',
        email: 'priya.sharma@gmail.com',
        phone: '+91 98765 43210',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
        addresses: [
            { id: 'a1', label: 'Home', address: 'Sobha Dream Acres, Wing 4, Flat 1204, Varthur', isDefault: true },
            { id: 'a2', label: 'Work', address: 'Prestige Tech Park, Outer Ring Road, Marathahalli', isDefault: false },
        ],
        totalOrders: 45,
        totalSpent: 28450,
        joinedAt: new Date('2024-03-15'),
        lastOrderAt: new Date('2025-12-30'),
        status: 'active',
    },
    {
        id: 'u2',
        name: 'Rahul Verma',
        email: 'rahul.verma@yahoo.com',
        phone: '+91 87654 32109',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
        addresses: [
            { id: 'a3', label: 'Home', address: 'Prestige Lakeside, Tower 2, Gunjur', isDefault: true },
        ],
        totalOrders: 23,
        totalSpent: 15680,
        joinedAt: new Date('2024-06-20'),
        lastOrderAt: new Date('2025-12-28'),
        status: 'active',
    },
    {
        id: 'u3',
        name: 'Ananya Reddy',
        email: 'ananya.r@gmail.com',
        phone: '+91 76543 21098',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
        addresses: [
            { id: 'a4', label: 'Home', address: 'Brigade Metropolis, Mahadevapura', isDefault: true },
        ],
        totalOrders: 67,
        totalSpent: 42350,
        joinedAt: new Date('2024-01-10'),
        lastOrderAt: new Date('2026-01-01'),
        status: 'active',
    },
    {
        id: 'u4',
        name: 'Vijay Kumar',
        email: 'vijay.k@outlook.com',
        phone: '+91 65432 10987',
        addresses: [
            { id: 'a5', label: 'Home', address: 'RMZ Ecoworld, Bellandur', isDefault: true },
        ],
        totalOrders: 12,
        totalSpent: 8900,
        joinedAt: new Date('2024-09-05'),
        lastOrderAt: new Date('2025-12-15'),
        status: 'inactive',
    },
    {
        id: 'u5',
        name: 'Kavitha Nair',
        email: 'kavitha.n@gmail.com',
        phone: '+91 54321 09876',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
        addresses: [
            { id: 'a6', label: 'Home', address: 'Mantri Serenity, Kannamangala', isDefault: true },
        ],
        totalOrders: 89,
        totalSpent: 56780,
        joinedAt: new Date('2023-11-20'),
        lastOrderAt: new Date('2026-01-02'),
        status: 'active',
    },
    {
        id: 'u6',
        name: 'Suresh Babu',
        email: 'suresh.b@gmail.com',
        phone: '+91 43210 98765',
        addresses: [],
        totalOrders: 3,
        totalSpent: 1250,
        joinedAt: new Date('2025-10-15'),
        status: 'blocked',
    },
    {
        id: 'u7',
        name: 'Meera Iyer',
        email: 'meera.iyer@gmail.com',
        phone: '+91 32109 87654',
        avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100',
        addresses: [
            { id: 'a7', label: 'Home', address: 'Salarpuria Sattva, Whitefield', isDefault: true },
        ],
        totalOrders: 34,
        totalSpent: 22400,
        joinedAt: new Date('2024-04-12'),
        lastOrderAt: new Date('2025-12-25'),
        status: 'active',
    },
    {
        id: 'u8',
        name: 'Arun Menon',
        email: 'arun.m@yahoo.com',
        phone: '+91 21098 76543',
        addresses: [
            { id: 'a8', label: 'Home', address: 'Embassy Tech Village, Marathahalli', isDefault: true },
        ],
        totalOrders: 56,
        totalSpent: 38900,
        joinedAt: new Date('2024-02-28'),
        lastOrderAt: new Date('2025-12-29'),
        status: 'active',
    },
];

// Mock Delivery Partners
export const mockDeliveryPartners: DeliveryPartner[] = [
    {
        id: 'dp1',
        name: 'Rajesh Kumar',
        phone: '+91 98765 11111',
        email: 'rajesh.k@eatfresh.com',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
        status: 'online',
        vehicleType: 'bike',
        vehicleNumber: 'KA 01 AB 1234',
        totalDeliveries: 1245,
        totalEarnings: 186750,
        rating: 4.8,
        ratingCount: 423,
        joinedAt: new Date('2024-01-15'),
        documentsVerified: true,
        currentLocation: { lat: 12.9716, lng: 77.5946 },
        bankDetails: {
            accountNumber: 'XXXX XXXX 1234',
            ifscCode: 'SBIN0001234',
            bankName: 'State Bank of India',
            accountHolderName: 'Rajesh Kumar',
        },
        documents: [
            { id: 'd1', type: 'aadhar', name: 'Aadhar Card', verified: true, uploadedAt: new Date('2024-01-15') },
            { id: 'd2', type: 'pan', name: 'PAN Card', verified: true, uploadedAt: new Date('2024-01-15') },
            { id: 'd3', type: 'dl', name: 'Driving License', verified: true, uploadedAt: new Date('2024-01-15') },
            { id: 'd4', type: 'rc', name: 'Vehicle RC', verified: true, uploadedAt: new Date('2024-01-15') },
        ],
        todayEarnings: 850,
        todayDeliveries: 12,
        weeklyEarnings: 5600,
        monthlyEarnings: 24500,
    },
    {
        id: 'dp2',
        name: 'Sunil Yadav',
        phone: '+91 98765 22222',
        email: 'sunil.y@eatfresh.com',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
        status: 'busy',
        vehicleType: 'scooter',
        vehicleNumber: 'KA 02 CD 5678',
        totalDeliveries: 876,
        totalEarnings: 131400,
        rating: 4.6,
        ratingCount: 298,
        joinedAt: new Date('2024-03-20'),
        documentsVerified: true,
        currentLocation: { lat: 12.9352, lng: 77.6245 },
        bankDetails: {
            accountNumber: 'XXXX XXXX 5678',
            ifscCode: 'HDFC0001234',
            bankName: 'HDFC Bank',
            accountHolderName: 'Sunil Yadav',
        },
        documents: [
            { id: 'd5', type: 'aadhar', name: 'Aadhar Card', verified: true, uploadedAt: new Date('2024-03-20') },
            { id: 'd6', type: 'pan', name: 'PAN Card', verified: true, uploadedAt: new Date('2024-03-20') },
            { id: 'd7', type: 'dl', name: 'Driving License', verified: true, uploadedAt: new Date('2024-03-20') },
            { id: 'd8', type: 'rc', name: 'Vehicle RC', verified: true, uploadedAt: new Date('2024-03-20') },
        ],
        todayEarnings: 720,
        todayDeliveries: 10,
        weeklyEarnings: 4800,
        monthlyEarnings: 21000,
    },
    {
        id: 'dp3',
        name: 'Manoj Singh',
        phone: '+91 98765 33333',
        email: 'manoj.s@eatfresh.com',
        status: 'offline',
        vehicleType: 'bike',
        vehicleNumber: 'KA 03 EF 9012',
        totalDeliveries: 234,
        totalEarnings: 35100,
        rating: 4.3,
        ratingCount: 89,
        joinedAt: new Date('2024-08-10'),
        documentsVerified: false,
        bankDetails: {
            accountNumber: 'XXXX XXXX 9012',
            ifscCode: 'ICIC0001234',
            bankName: 'ICICI Bank',
            accountHolderName: 'Manoj Singh',
        },
        documents: [
            { id: 'd9', type: 'aadhar', name: 'Aadhar Card', verified: true, uploadedAt: new Date('2024-08-10') },
            { id: 'd10', type: 'pan', name: 'PAN Card', verified: false, uploadedAt: new Date('2024-08-10') },
            { id: 'd11', type: 'dl', name: 'Driving License', verified: true, uploadedAt: new Date('2024-08-10') },
            { id: 'd12', type: 'rc', name: 'Vehicle RC', verified: false, uploadedAt: new Date('2024-08-10') },
        ],
        todayEarnings: 0,
        todayDeliveries: 0,
        weeklyEarnings: 2100,
        monthlyEarnings: 8500,
    },
    {
        id: 'dp4',
        name: 'Prakash Rao',
        phone: '+91 98765 44444',
        email: 'prakash.r@eatfresh.com',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100',
        status: 'online',
        vehicleType: 'bike',
        vehicleNumber: 'KA 04 GH 3456',
        totalDeliveries: 1567,
        totalEarnings: 235050,
        rating: 4.9,
        ratingCount: 534,
        joinedAt: new Date('2023-10-05'),
        documentsVerified: true,
        currentLocation: { lat: 12.9856, lng: 77.7085 },
        bankDetails: {
            accountNumber: 'XXXX XXXX 3456',
            ifscCode: 'AXIS0001234',
            bankName: 'Axis Bank',
            accountHolderName: 'Prakash Rao',
        },
        documents: [
            { id: 'd13', type: 'aadhar', name: 'Aadhar Card', verified: true, uploadedAt: new Date('2023-10-05') },
            { id: 'd14', type: 'pan', name: 'PAN Card', verified: true, uploadedAt: new Date('2023-10-05') },
            { id: 'd15', type: 'dl', name: 'Driving License', verified: true, uploadedAt: new Date('2023-10-05') },
            { id: 'd16', type: 'rc', name: 'Vehicle RC', verified: true, uploadedAt: new Date('2023-10-05') },
        ],
        todayEarnings: 1120,
        todayDeliveries: 16,
        weeklyEarnings: 7200,
        monthlyEarnings: 31500,
    },
    {
        id: 'dp5',
        name: 'Venkat Reddy',
        phone: '+91 98765 55555',
        email: 'venkat.r@eatfresh.com',
        status: 'online',
        vehicleType: 'scooter',
        vehicleNumber: 'KA 05 IJ 7890',
        totalDeliveries: 678,
        totalEarnings: 101700,
        rating: 4.5,
        ratingCount: 234,
        joinedAt: new Date('2024-05-18'),
        documentsVerified: true,
        currentLocation: { lat: 12.9623, lng: 77.6354 },
        bankDetails: {
            accountNumber: 'XXXX XXXX 7890',
            ifscCode: 'KOTAK0001234',
            bankName: 'Kotak Mahindra Bank',
            accountHolderName: 'Venkat Reddy',
        },
        documents: [
            { id: 'd17', type: 'aadhar', name: 'Aadhar Card', verified: true, uploadedAt: new Date('2024-05-18') },
            { id: 'd18', type: 'pan', name: 'PAN Card', verified: true, uploadedAt: new Date('2024-05-18') },
            { id: 'd19', type: 'dl', name: 'Driving License', verified: true, uploadedAt: new Date('2024-05-18') },
            { id: 'd20', type: 'rc', name: 'Vehicle RC', verified: true, uploadedAt: new Date('2024-05-18') },
        ],
        todayEarnings: 560,
        todayDeliveries: 8,
        weeklyEarnings: 3900,
        monthlyEarnings: 16800,
    },
    {
        id: 'dp6',
        name: 'Naveen Gowda',
        phone: '+91 98765 66666',
        email: 'naveen.g@eatfresh.com',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
        status: 'busy',
        vehicleType: 'bike',
        vehicleNumber: 'KA 06 KL 1234',
        totalDeliveries: 445,
        totalEarnings: 66750,
        rating: 4.7,
        ratingCount: 156,
        joinedAt: new Date('2024-06-25'),
        documentsVerified: true,
        currentLocation: { lat: 12.9512, lng: 77.6489 },
        bankDetails: {
            accountNumber: 'XXXX XXXX 1122',
            ifscCode: 'UTIB0001234',
            bankName: 'Axis Bank',
            accountHolderName: 'Naveen Gowda',
        },
        documents: [
            { id: 'd21', type: 'aadhar', name: 'Aadhar Card', verified: true, uploadedAt: new Date('2024-06-25') },
            { id: 'd22', type: 'pan', name: 'PAN Card', verified: true, uploadedAt: new Date('2024-06-25') },
            { id: 'd23', type: 'dl', name: 'Driving License', verified: true, uploadedAt: new Date('2024-06-25') },
            { id: 'd24', type: 'rc', name: 'Vehicle RC', verified: true, uploadedAt: new Date('2024-06-25') },
        ],
        todayEarnings: 680,
        todayDeliveries: 9,
        weeklyEarnings: 4200,
        monthlyEarnings: 18500,
    },
];

// Mock Orders
export const mockOrders: Order[] = [
    {
        id: 'EF2024A1B2C3',
        userId: 'u1',
        userName: 'Priya Sharma',
        userPhone: '+91 98765 43210',
        items: [
            { id: 'i1', productId: 'p1', productName: 'Boneless Chicken Breast', quantity: 2, price: 320, image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=100' },
            { id: 'i2', productId: 'p2', productName: 'Chicken Drumsticks', quantity: 1, price: 180, image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=100' },
        ],
        status: 'delivered',
        deliveryAddress: { id: 'a1', label: 'Home', address: 'Sobha Dream Acres, Wing 4, Flat 1204', isDefault: true },
        itemTotal: 500,
        deliveryFee: 0,
        taxes: 25,
        grandTotal: 525,
        paymentInfo: { razorpay_payment_id: 'pay_123abc', method: 'UPI', status: 'success' },
        createdAt: new Date('2025-12-30T10:30:00'),
        updatedAt: new Date('2025-12-30T11:15:00'),
        estimatedDelivery: '45 mins',
        deliveryPartnerId: 'dp1',
        deliveryPartnerName: 'Rajesh Kumar',
        shopId: '1',
        shopName: 'Varthur Fresh Chicken',
    },
    {
        id: 'EF2024D4E5F6',
        userId: 'u3',
        userName: 'Ananya Reddy',
        userPhone: '+91 76543 21098',
        items: [
            { id: 'i3', productId: 'p3', productName: 'Premium Mutton Chops', quantity: 1, price: 650, image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=100' },
        ],
        status: 'out_for_delivery',
        deliveryAddress: { id: 'a4', label: 'Home', address: 'Brigade Metropolis, Mahadevapura', isDefault: true },
        itemTotal: 650,
        deliveryFee: 20,
        taxes: 33.5,
        grandTotal: 703.5,
        paymentInfo: { razorpay_payment_id: 'pay_456def', method: 'Card', status: 'success' },
        createdAt: new Date('2026-01-02T06:45:00'),
        updatedAt: new Date('2026-01-02T07:30:00'),
        estimatedDelivery: '20 mins',
        deliveryPartnerId: 'dp2',
        deliveryPartnerName: 'Sunil Yadav',
        shopId: '2',
        shopName: 'Royal Mutton Stall',
    },
    {
        id: 'EF2024G7H8I9',
        userId: 'u5',
        userName: 'Kavitha Nair',
        userPhone: '+91 54321 09876',
        items: [
            { id: 'i4', productId: 'p4', productName: 'Fresh Prawns', quantity: 1, price: 480, image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=100' },
            { id: 'i5', productId: 'p5', productName: 'Pomfret Fish', quantity: 2, price: 560, image: 'https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=100' },
        ],
        status: 'preparing',
        deliveryAddress: { id: 'a6', label: 'Home', address: 'Mantri Serenity, Kannamangala', isDefault: true },
        itemTotal: 1040,
        deliveryFee: 0,
        taxes: 52,
        grandTotal: 1092,
        paymentInfo: { razorpay_payment_id: 'pay_789ghi', method: 'UPI', status: 'success' },
        createdAt: new Date('2026-01-02T07:15:00'),
        updatedAt: new Date('2026-01-02T07:20:00'),
        estimatedDelivery: '60 mins',
        shopId: '3',
        shopName: 'Coastal Catch Fish Mart',
    },
    {
        id: 'EF2024J1K2L3',
        userId: 'u2',
        userName: 'Rahul Verma',
        userPhone: '+91 87654 32109',
        items: [
            { id: 'i6', productId: 'p6', productName: 'Organic Chicken', quantity: 1, price: 420, image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=100' },
        ],
        status: 'pending',
        deliveryAddress: { id: 'a3', label: 'Home', address: 'Prestige Lakeside, Tower 2, Gunjur', isDefault: true },
        itemTotal: 420,
        deliveryFee: 0,
        taxes: 21,
        grandTotal: 441,
        paymentInfo: { status: 'pending' },
        createdAt: new Date('2026-01-02T07:40:00'),
        updatedAt: new Date('2026-01-02T07:40:00'),
        estimatedDelivery: '45 mins',
        shopId: '4',
        shopName: 'Organic Meats & Co.',
    },
    {
        id: 'EF2024M4N5O6',
        userId: 'u7',
        userName: 'Meera Iyer',
        userPhone: '+91 32109 87654',
        items: [
            { id: 'i7', productId: 'p1', productName: 'Boneless Chicken Breast', quantity: 3, price: 480, image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=100' },
        ],
        status: 'cancelled',
        deliveryAddress: { id: 'a7', label: 'Home', address: 'Salarpuria Sattva, Whitefield', isDefault: true },
        itemTotal: 480,
        deliveryFee: 0,
        taxes: 24,
        grandTotal: 504,
        paymentInfo: { razorpay_payment_id: 'pay_abc123', method: 'UPI', status: 'failed' },
        createdAt: new Date('2025-12-29T15:20:00'),
        updatedAt: new Date('2025-12-29T15:45:00'),
        shopId: '1',
        shopName: 'Varthur Fresh Chicken',
    },
    {
        id: 'EF2024P7Q8R9',
        userId: 'u8',
        userName: 'Arun Menon',
        userPhone: '+91 21098 76543',
        items: [
            { id: 'i8', productId: 'p3', productName: 'Premium Mutton Chops', quantity: 2, price: 1300, image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=100' },
            { id: 'i9', productId: 'p7', productName: 'Mutton Keema', quantity: 1, price: 380, image: 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=100' },
        ],
        status: 'confirmed',
        deliveryAddress: { id: 'a8', label: 'Home', address: 'Embassy Tech Village, Marathahalli', isDefault: true },
        itemTotal: 1680,
        deliveryFee: 20,
        taxes: 85,
        grandTotal: 1785,
        paymentInfo: { razorpay_payment_id: 'pay_def456', method: 'Card', status: 'success' },
        createdAt: new Date('2026-01-02T07:35:00'),
        updatedAt: new Date('2026-01-02T07:38:00'),
        estimatedDelivery: '50 mins',
        shopId: '2',
        shopName: 'Royal Mutton Stall',
    },
];

// Mock Shops
export const mockShops: Shop[] = [
    {
        id: '1',
        name: 'Varthur Fresh Chicken',
        rating: 4.8,
        reviewCount: 120,
        categories: ['Chicken', 'Eggs', 'Marinades'],
        distance: '0.8 km',
        address: 'Main Road, Varthur',
        timing: '8 AM - 8 PM',
        isOpen: true,
        freeDelivery: true,
        deliveryTime: '45 mins',
        image: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=400',
        totalOrders: 2340,
        totalRevenue: 1456000,
    },
    {
        id: '2',
        name: 'Royal Mutton Stall',
        rating: 4.5,
        reviewCount: 85,
        categories: ['Premium Mutton', 'Chops', 'Keema'],
        distance: '1.2 km',
        address: 'Market Square',
        timing: '8 AM - 8 PM',
        isOpen: true,
        freeDelivery: false,
        deliveryFee: 20,
        deliveryTime: '50 mins',
        image: 'https://images.unsplash.com/photo-1602470520998-f4a52199a3d6?w=400',
        totalOrders: 1890,
        totalRevenue: 2234000,
    },
    {
        id: '3',
        name: 'Coastal Catch Fish Mart',
        rating: 4.2,
        reviewCount: 65,
        categories: ['Sea Fish', 'Prawns', 'Crabs'],
        distance: '2.5 km',
        address: 'Near Lake',
        timing: '8 AM - 8 PM',
        isOpen: false,
        closingSoon: true,
        freeDelivery: true,
        deliveryTime: '60 mins',
        image: 'https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=400',
        totalOrders: 876,
        totalRevenue: 945000,
    },
    {
        id: '4',
        name: 'Organic Meats & Co.',
        rating: 4.9,
        reviewCount: 210,
        categories: ['Free Range Chicken', 'Organic Mutton'],
        distance: '1.5 km',
        address: 'Green Street',
        timing: '8 AM - 8 PM',
        isOpen: true,
        freeDelivery: true,
        deliveryTime: '45 mins',
        image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=400',
        totalOrders: 1567,
        totalRevenue: 1890000,
    },
];

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
    totalUsers: 1248,
    totalPartners: 86,
    totalOrders: 8945,
    totalRevenue: 6525000,
    usersGrowth: 12.5,
    partnersGrowth: 8.2,
    ordersGrowth: 23.4,
    revenueGrowth: 18.7,
};

// Helper functions
export const getUserById = (id: string): User | undefined => {
    return mockUsers.find((user) => user.id === id);
};

export const getPartnerById = (id: string): DeliveryPartner | undefined => {
    return mockDeliveryPartners.find((partner) => partner.id === id);
};

export const getOrderById = (id: string): Order | undefined => {
    return mockOrders.find((order) => order.id === id);
};

export const getOrdersByUserId = (userId: string): Order[] => {
    return mockOrders.filter((order) => order.userId === userId);
};

export const getOrdersByPartnerId = (partnerId: string): Order[] => {
    return mockOrders.filter((order) => order.deliveryPartnerId === partnerId);
};
